### ISSUE TITLE
missing string

### ISSUE THREAD

**Issue by danmarsden** [patrickthibaudeau/moodle-format_glendon#11]
Invalid get_string() identifier: 'privacy:metadata' or component 'format_glendon'. Perhaps you are missing $string['privacy:metadata'] = ''; in /home/dan/www/moodle/course/format/glendon/lang/en/format_glendon.php?

you can see this by going to admin > users tab, privacy and policies and viewing the "Plugin privacy registry" report.

**Comment by patrickthibaudeau** [comment]
Fixed, thank you.
