### ISSUE TITLE
inconsistent copyrights

### ISSUE THREAD

**Issue by danmarsden** [patrickthibaudeau/moodle-format_glendon#13]
Please review Issue #6 again - I still see some incorrect copyright statements that list other devs that I do not believe have written any of this code...

**Comment by patrickthibaudeau** [comment]
I have gone through every file and only see my name and the institution I work for. If you can pin point where I'm giving credit to someone else, please let me know.

**Comment by danmarsden** [comment]
https://github.com/patrickthibaudeau/moodle-format_glendon/blob/master/classes/privacy/provider.php#L33

https://github.com/patrickthibaudeau/moodle-format_glendon/blob/master/renderer.php#L32

https://github.com/patrickthibaudeau/moodle-format_glendon/blob/master/lib.php#L33
