### ISSUE TITLE
styles.css has generic css that may interfere with other formats/themes

### ISSUE THREAD

**Issue by danmarsden** [patrickthibaudeau/moodle-format_glendon#2]
ideally all items in your styles.css and styles_boost.css files shold be prefixed by:
.format-glendon

eg:
https://github.com/patrickthibaudeau/moodle-format_glendon/blob/master/styles.css#L171
.btn-link {
should be:
.format-glendon .btn-link {

I also see "Add Bootstrap 4 css for other themes" in styles.css - is that really the right place for this?

**Comment by patrickthibaudeau** [comment]
Removed all Bootstrap 4. I had put it there to try and make compatible with bootstrapbase themes. With 3.7 removing bootstrapbase, this should not be an issue.
