### ISSUE TITLE
Problems with display/accessing activities

### ISSUE THREAD

**Issue by logan-reynolds** [patrickthibaudeau/moodle-format_glendon#8]
When testing format_glendon version 2018071900 release 2.3 Build(2018071900) on Moodle 3.4 it was noticed that individual activities don't show up within the sections when a section is selected.  There is also an issue when images are used - the top of image is cropped in boost, while the same image is resized in our custom theme.

**Comment by patrickthibaudeau** [comment]
THis plugin should only work starting at Moodle 3.5 as the required Moodle for the plugin version is 2018051700. Because this cannot work with bootstrapbase, I will make it so that it requires Moodle 3.7 when it is released. In the meantime I'm leaving it at 3.5 as I need to use it in my courses :)

**Comment by patrickthibaudeau** [comment]
Only works with Moodle 3.7 and up.
