### ISSUE TITLE
css not specific enough

### ISSUE THREAD

**Issue by danmarsden** [patrickthibaudeau/moodle-format_glendon#9]
as mention in issue #2 - your styles.css file is not quite specific enough and the latest version doesn't appear to have fixed all tags?

I see some commits like: 84caf114cc87f7189e220d9d05a18332e76f6e0b that fix some parts of your css, but I still see stuff like 
.course-page-img
.topic-text

Ideally it would be good for "all" css in your styles.css and styles_boost.css to be prefixed with:
.format-glendon
To avoid any conflicts with other pages inside Moodle.

**Comment by patrickthibaudeau** [comment]
Renamed css and removed unused CSS. Thanks
